; === TRANSPORTS ===
[transport-wss]
type=transport
protocol=wss
bind=0.0.0.0

; === EXTENSION 1001 ===
[1001]
type=endpoint
context=internal
disallow=all
allow=opus
allow=ulaw
transport=transport-wss
webrtc=yes
aors=1001
auth=1001-auth

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=secret1001

[1001]
type=aor
max_contacts=5
remove_existing=no

; === EXTENSION 1002 ===
[1002]
type=endpoint
context=internal
disallow=all
allow=opus
allow=ulaw
transport=transport-wss
webrtc=yes
aors=1002
auth=1002-auth

[1002-auth]
type=auth
auth_type=userpass
username=1002
password=secret1002

[1002]
type=aor
max_contacts=5
remove_existing=no
