[global]
type=global
user_agent=MyPBX
endpoint_identifier_order=auth_username,username,ip,anonymous

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=172.20.0.0/24
external_media_address=172.20.0.2
external_signaling_address=172.20.0.2

[kamailio]
type=endpoint
context=internal
disallow=all
allow=opus
allow=ulaw
allow=alaw
webrtc=yes
transport=transport-udp
direct_media=no

[kamailio-identify]
type=identify
endpoint=kamailio
match=172.20.0.3

[1001]
type=endpoint
context=internal
disallow=all
allow=opus
allow=ulaw
allow=alaw
webrtc=yes
transport=transport-udp
aors=1001
auth=1001-auth
dtls_auto_generate_cert=yes
ice_support=yes
media_use_received_transport=yes
rtcp_mux=yes

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=secret1001

[1002]
type=endpoint
context=internal
disallow=all
allow=opus
allow=ulaw
allow=alaw
webrtc=yes
transport=transport-udp
aors=1002
auth=1002-auth
dtls_auto_generate_cert=yes
ice_support=yes
media_use_received_transport=yes
rtcp_mux=yes

[1002-auth]
type=auth
auth_type=userpass
username=1002
password=secret1002

#include pjsip_aor.conf
